// Code generated by protoc-gen-go. DO NOT EDIT.
// source: output.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Model struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            int64    `protobuf:"varint,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt            int64    `protobuf:"varint,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2b3ae2e703b013, []int{0}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Model) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Model) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Model) GetDeletedAt() int64 {
	if m != nil {
		return m.DeletedAt
	}
	return 0
}

type Wallet struct {
	Model                *Model   `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CustomerID           int64    `protobuf:"varint,3,opt,name=customerID,proto3" json:"customerID,omitempty"`
	AvailableBal         float64  `protobuf:"fixed64,4,opt,name=availableBal,proto3" json:"availableBal,omitempty"`
	LedgerBal            float64  `protobuf:"fixed64,5,opt,name=ledgerBal,proto3" json:"ledgerBal,omitempty"`
	AccountType          string   `protobuf:"bytes,6,opt,name=accountType,proto3" json:"accountType,omitempty"`
	WalletID             int64    `protobuf:"varint,7,opt,name=walletID,proto3" json:"walletID,omitempty"`
	WalletNo             string   `protobuf:"bytes,8,opt,name=walletNo,proto3" json:"walletNo,omitempty"`
	Currency             string   `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Status               string   `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	DateCreated          string   `protobuf:"bytes,11,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	DateBalUpdated       string   `protobuf:"bytes,12,opt,name=dateBalUpdated,proto3" json:"dateBalUpdated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Wallet) Reset()         { *m = Wallet{} }
func (m *Wallet) String() string { return proto.CompactTextString(m) }
func (*Wallet) ProtoMessage()    {}
func (*Wallet) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2b3ae2e703b013, []int{1}
}

func (m *Wallet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wallet.Unmarshal(m, b)
}
func (m *Wallet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wallet.Marshal(b, m, deterministic)
}
func (m *Wallet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallet.Merge(m, src)
}
func (m *Wallet) XXX_Size() int {
	return xxx_messageInfo_Wallet.Size(m)
}
func (m *Wallet) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallet.DiscardUnknown(m)
}

var xxx_messageInfo_Wallet proto.InternalMessageInfo

func (m *Wallet) GetModel() *Model {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *Wallet) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Wallet) GetCustomerID() int64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *Wallet) GetAvailableBal() float64 {
	if m != nil {
		return m.AvailableBal
	}
	return 0
}

func (m *Wallet) GetLedgerBal() float64 {
	if m != nil {
		return m.LedgerBal
	}
	return 0
}

func (m *Wallet) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *Wallet) GetWalletID() int64 {
	if m != nil {
		return m.WalletID
	}
	return 0
}

func (m *Wallet) GetWalletNo() string {
	if m != nil {
		return m.WalletNo
	}
	return ""
}

func (m *Wallet) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Wallet) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Wallet) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func (m *Wallet) GetDateBalUpdated() string {
	if m != nil {
		return m.DateBalUpdated
	}
	return ""
}

type UserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2b3ae2e703b013, []int{2}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "proto.Model")
	proto.RegisterType((*Wallet)(nil), "proto.Wallet")
	proto.RegisterType((*UserId)(nil), "proto.UserId")
}

func init() { proto.RegisterFile("output.proto", fileDescriptor_0b2b3ae2e703b013) }

var fileDescriptor_0b2b3ae2e703b013 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4f, 0xfa, 0x40,
	0x10, 0xc5, 0xff, 0x2d, 0xff, 0x56, 0x18, 0x5a, 0x0e, 0x7b, 0x30, 0x1b, 0x62, 0x4c, 0xd3, 0x83,
	0xe1, 0x84, 0x09, 0x7e, 0x01, 0x45, 0x12, 0xc3, 0x41, 0x0f, 0x45, 0xe2, 0x79, 0xe9, 0x4e, 0xb4,
	0xc9, 0x42, 0xeb, 0x76, 0x17, 0xc3, 0x97, 0x37, 0x66, 0x77, 0x4b, 0x5b, 0x3d, 0x35, 0xef, 0xfd,
	0x66, 0x3b, 0x6f, 0x66, 0x20, 0x2a, 0xb5, 0xaa, 0xb4, 0x9a, 0x57, 0xb2, 0x54, 0x25, 0x09, 0xec,
	0x27, 0xfd, 0x84, 0xe0, 0xb9, 0xe4, 0x28, 0xc8, 0x04, 0xfc, 0x82, 0x53, 0x2f, 0xf1, 0x66, 0x71,
	0xe6, 0x17, 0x9c, 0x5c, 0xc1, 0x28, 0x97, 0xc8, 0x14, 0xf2, 0x07, 0x45, 0xfd, 0xc4, 0x9b, 0x0d,
	0xb2, 0xce, 0x30, 0x54, 0x57, 0xbc, 0xa1, 0x03, 0x47, 0x5b, 0xc3, 0x50, 0x8e, 0x02, 0x1d, 0xfd,
	0xef, 0x68, 0x6b, 0xa4, 0xdf, 0x3e, 0x84, 0x6f, 0x4c, 0x08, 0x54, 0x24, 0x85, 0x60, 0x6f, 0xba,
	0xdb, 0xbe, 0xe3, 0x45, 0xe4, 0xb2, 0xcd, 0x6d, 0xa2, 0xcc, 0x21, 0x72, 0x09, 0xa1, 0xae, 0x51,
	0xae, 0xb9, 0x4d, 0x31, 0xca, 0x1a, 0x45, 0xae, 0x01, 0x72, 0x5d, 0xab, 0x72, 0x8f, 0x72, 0xbd,
	0x6a, 0x32, 0xf4, 0x1c, 0x92, 0x42, 0xc4, 0x8e, 0xac, 0x10, 0x6c, 0x27, 0x70, 0xc9, 0x84, 0xcd,
	0xe1, 0x65, 0xbf, 0x3c, 0x13, 0x54, 0x20, 0x7f, 0x47, 0x69, 0x0a, 0x02, 0x5b, 0xd0, 0x19, 0x24,
	0x81, 0x31, 0xcb, 0xf3, 0x52, 0x1f, 0xd4, 0xeb, 0xa9, 0x42, 0x1a, 0xda, 0xf6, 0x7d, 0x8b, 0x4c,
	0x61, 0xf8, 0x65, 0x27, 0x59, 0xaf, 0xe8, 0x85, 0x4d, 0xd0, 0xea, 0x8e, 0xbd, 0x94, 0x74, 0x68,
	0x9f, 0xb6, 0xda, 0xb0, 0x5c, 0x4b, 0x89, 0x87, 0xfc, 0x44, 0x47, 0x8e, 0x9d, 0xb5, 0x99, 0xb7,
	0x56, 0x4c, 0xe9, 0x9a, 0x82, 0x9b, 0xd7, 0x29, 0x93, 0xc6, 0xec, 0xf7, 0xd1, 0xdd, 0x80, 0x8e,
	0x5d, 0x9a, 0x9e, 0x45, 0x6e, 0x60, 0x62, 0xe4, 0x92, 0x89, 0xad, 0x3b, 0x05, 0x8d, 0x6c, 0xd1,
	0x1f, 0x37, 0x4d, 0x20, 0xdc, 0xba, 0x1d, 0x76, 0xbb, 0xf5, 0xfa, 0xbb, 0x5d, 0xdc, 0x43, 0xbc,
	0xf9, 0x60, 0x12, 0xf9, 0x06, 0xe5, 0xb1, 0xc8, 0x91, 0xdc, 0x42, 0xfc, 0x84, 0xca, 0xbc, 0x6a,
	0x2e, 0x17, 0x37, 0xa7, 0x72, 0x3f, 0x9a, 0x9e, 0xa5, 0xa3, 0xe9, 0xbf, 0x5d, 0x68, 0xf5, 0xdd,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x17, 0xc4, 0x0f, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SharedServiceClient is the client API for SharedService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SharedServiceClient interface {
	GetUserWallet(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Wallet, error)
}

type sharedServiceClient struct {
	cc *grpc.ClientConn
}

func NewSharedServiceClient(cc *grpc.ClientConn) SharedServiceClient {
	return &sharedServiceClient{cc}
}

func (c *sharedServiceClient) GetUserWallet(ctx context.Context, in *UserId, opts ...grpc.CallOption) (*Wallet, error) {
	out := new(Wallet)
	err := c.cc.Invoke(ctx, "/proto.SharedService/GetUserWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SharedServiceServer is the server API for SharedService service.
type SharedServiceServer interface {
	GetUserWallet(context.Context, *UserId) (*Wallet, error)
}

// UnimplementedSharedServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSharedServiceServer struct {
}

func (*UnimplementedSharedServiceServer) GetUserWallet(ctx context.Context, req *UserId) (*Wallet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserWallet not implemented")
}

func RegisterSharedServiceServer(s *grpc.Server, srv SharedServiceServer) {
	s.RegisterService(&_SharedService_serviceDesc, srv)
}

func _SharedService_GetUserWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SharedServiceServer).GetUserWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.SharedService/GetUserWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SharedServiceServer).GetUserWallet(ctx, req.(*UserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _SharedService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.SharedService",
	HandlerType: (*SharedServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserWallet",
			Handler:    _SharedService_GetUserWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "output.proto",
}
