// Code generated by protoc-gen-go. DO NOT EDIT.
// source: output.proto

package models

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Model struct {
	Id                   uint32               `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	DeletedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=deletedAt,proto3" json:"deletedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Model) Reset()         { *m = Model{} }
func (m *Model) String() string { return proto.CompactTextString(m) }
func (*Model) ProtoMessage()    {}
func (*Model) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2b3ae2e703b013, []int{0}
}

func (m *Model) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Model.Unmarshal(m, b)
}
func (m *Model) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Model.Marshal(b, m, deterministic)
}
func (m *Model) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Model.Merge(m, src)
}
func (m *Model) XXX_Size() int {
	return xxx_messageInfo_Model.Size(m)
}
func (m *Model) XXX_DiscardUnknown() {
	xxx_messageInfo_Model.DiscardUnknown(m)
}

var xxx_messageInfo_Model proto.InternalMessageInfo

func (m *Model) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Model) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Model) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Model) GetDeletedAt() *timestamp.Timestamp {
	if m != nil {
		return m.DeletedAt
	}
	return nil
}

type UserId struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserId) Reset()         { *m = UserId{} }
func (m *UserId) String() string { return proto.CompactTextString(m) }
func (*UserId) ProtoMessage()    {}
func (*UserId) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2b3ae2e703b013, []int{1}
}

func (m *UserId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserId.Unmarshal(m, b)
}
func (m *UserId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserId.Marshal(b, m, deterministic)
}
func (m *UserId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserId.Merge(m, src)
}
func (m *UserId) XXX_Size() int {
	return xxx_messageInfo_UserId.Size(m)
}
func (m *UserId) XXX_DiscardUnknown() {
	xxx_messageInfo_UserId.DiscardUnknown(m)
}

var xxx_messageInfo_UserId proto.InternalMessageInfo

func (m *UserId) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type WalletArg struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletArg) Reset()         { *m = WalletArg{} }
func (m *WalletArg) String() string { return proto.CompactTextString(m) }
func (*WalletArg) ProtoMessage()    {}
func (*WalletArg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2b3ae2e703b013, []int{2}
}

func (m *WalletArg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletArg.Unmarshal(m, b)
}
func (m *WalletArg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletArg.Marshal(b, m, deterministic)
}
func (m *WalletArg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletArg.Merge(m, src)
}
func (m *WalletArg) XXX_Size() int {
	return xxx_messageInfo_WalletArg.Size(m)
}
func (m *WalletArg) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletArg.DiscardUnknown(m)
}

var xxx_messageInfo_WalletArg proto.InternalMessageInfo

func (m *WalletArg) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *WalletArg) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type WalletMsg struct {
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CustomerID           float64  `protobuf:"fixed64,3,opt,name=customerID,proto3" json:"customerID,omitempty"`
	AccountType          string   `protobuf:"bytes,6,opt,name=accountType,proto3" json:"accountType,omitempty"`
	WalletID             float64  `protobuf:"fixed64,7,opt,name=walletID,proto3" json:"walletID,omitempty"`
	WalletNo             string   `protobuf:"bytes,8,opt,name=walletNo,proto3" json:"walletNo,omitempty"`
	Currency             string   `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	DateCreated          string   `protobuf:"bytes,11,opt,name=dateCreated,proto3" json:"dateCreated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WalletMsg) Reset()         { *m = WalletMsg{} }
func (m *WalletMsg) String() string { return proto.CompactTextString(m) }
func (*WalletMsg) ProtoMessage()    {}
func (*WalletMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b2b3ae2e703b013, []int{3}
}

func (m *WalletMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WalletMsg.Unmarshal(m, b)
}
func (m *WalletMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WalletMsg.Marshal(b, m, deterministic)
}
func (m *WalletMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletMsg.Merge(m, src)
}
func (m *WalletMsg) XXX_Size() int {
	return xxx_messageInfo_WalletMsg.Size(m)
}
func (m *WalletMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WalletMsg proto.InternalMessageInfo

func (m *WalletMsg) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *WalletMsg) GetCustomerID() float64 {
	if m != nil {
		return m.CustomerID
	}
	return 0
}

func (m *WalletMsg) GetAccountType() string {
	if m != nil {
		return m.AccountType
	}
	return ""
}

func (m *WalletMsg) GetWalletID() float64 {
	if m != nil {
		return m.WalletID
	}
	return 0
}

func (m *WalletMsg) GetWalletNo() string {
	if m != nil {
		return m.WalletNo
	}
	return ""
}

func (m *WalletMsg) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *WalletMsg) GetDateCreated() string {
	if m != nil {
		return m.DateCreated
	}
	return ""
}

func init() {
	proto.RegisterType((*Model)(nil), "models.Model")
	proto.RegisterType((*UserId)(nil), "models.UserId")
	proto.RegisterType((*WalletArg)(nil), "models.WalletArg")
	proto.RegisterType((*WalletMsg)(nil), "models.WalletMsg")
}

func init() { proto.RegisterFile("output.proto", fileDescriptor_0b2b3ae2e703b013) }

var fileDescriptor_0b2b3ae2e703b013 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0x4e, 0xe3, 0x30,
	0x10, 0x86, 0x37, 0xd9, 0x6d, 0xb6, 0x99, 0x6e, 0x57, 0xc2, 0x42, 0x28, 0xca, 0x01, 0xa2, 0x9c,
	0x7a, 0x4a, 0xa5, 0x72, 0x00, 0x8e, 0x15, 0x95, 0xa0, 0x87, 0x72, 0x08, 0x45, 0x9c, 0x53, 0x7b,
	0x88, 0x22, 0x25, 0x75, 0xe4, 0xd8, 0xa0, 0x3e, 0x20, 0x4f, 0xc1, 0xcb, 0x20, 0xdb, 0x4d, 0x1a,
	0x90, 0x50, 0x6f, 0xf9, 0xff, 0xf9, 0xbf, 0x19, 0xcd, 0x38, 0xf0, 0x8f, 0x2b, 0x59, 0x2b, 0x99,
	0xd4, 0x82, 0x4b, 0x4e, 0xbc, 0x8a, 0x33, 0x2c, 0x9b, 0xf0, 0x22, 0xe7, 0x3c, 0x2f, 0x71, 0x6a,
	0xdc, 0x8d, 0x7a, 0x99, 0xca, 0xa2, 0xc2, 0x46, 0x66, 0x55, 0x6d, 0x83, 0xf1, 0xbb, 0x03, 0x83,
	0x95, 0xce, 0x92, 0xff, 0xe0, 0x16, 0x2c, 0x70, 0x22, 0x67, 0x32, 0x4e, 0xdd, 0x82, 0x91, 0x6b,
	0xf0, 0xa9, 0xc0, 0x4c, 0x22, 0x9b, 0xcb, 0xc0, 0x8d, 0x9c, 0xc9, 0x68, 0x16, 0x26, 0xb6, 0x5d,
	0xd2, 0xb6, 0x4b, 0xd6, 0x6d, 0xbb, 0xf4, 0x10, 0xd6, 0xa4, 0xaa, 0xd9, 0x9e, 0xfc, 0x7d, 0x9c,
	0xec, 0xc2, 0x9a, 0x64, 0x58, 0xa2, 0x25, 0xff, 0x1c, 0x27, 0xbb, 0x70, 0x1c, 0x81, 0xf7, 0xd4,
	0xa0, 0x58, 0x32, 0x72, 0x06, 0x9e, 0x32, 0x5f, 0x66, 0x17, 0x3f, 0xdd, 0xab, 0xf8, 0x06, 0xfc,
	0xe7, 0xac, 0x2c, 0x51, 0xce, 0x45, 0xfe, 0x53, 0x88, 0x9c, 0xc2, 0x00, 0xab, 0xac, 0x28, 0xcd,
	0xc2, 0x7e, 0x6a, 0x45, 0xfc, 0xe1, 0xb4, 0xec, 0xaa, 0xe9, 0xb3, 0xee, 0x17, 0xf6, 0x1c, 0x80,
	0xaa, 0x46, 0xf2, 0x0a, 0xc5, 0x72, 0x61, 0xf6, 0x76, 0xd2, 0x9e, 0x43, 0x22, 0x18, 0x65, 0x94,
	0x72, 0xb5, 0x95, 0xeb, 0x5d, 0x8d, 0x81, 0x67, 0xe0, 0xbe, 0x45, 0x42, 0x18, 0xbe, 0x99, 0x31,
	0xcb, 0x45, 0xf0, 0xd7, 0xf0, 0x9d, 0x3e, 0xd4, 0x1e, 0x78, 0x30, 0x34, 0x68, 0xa7, 0x75, 0x8d,
	0x2a, 0x21, 0x70, 0x4b, 0x77, 0x81, 0x6f, 0x6b, 0xad, 0xd6, 0x53, 0xf5, 0x75, 0x6f, 0xed, 0xeb,
	0x04, 0x23, 0x3b, 0xb5, 0x67, 0xcd, 0xee, 0x61, 0x6c, 0x97, 0x7b, 0x44, 0xf1, 0x5a, 0x50, 0x24,
	0x57, 0x30, 0xbe, 0x43, 0xa9, 0xcf, 0x69, 0x7d, 0x72, 0x92, 0xd8, 0xdf, 0x29, 0xe9, 0x0e, 0x18,
	0x7e, 0xb3, 0x56, 0x4d, 0x1e, 0xff, 0xda, 0x78, 0xe6, 0x8d, 0x2e, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x25, 0xec, 0xf6, 0x3f, 0x8c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WalletServiceClient interface {
	GetUserWallet(ctx context.Context, in *WalletArg, opts ...grpc.CallOption) (*WalletMsg, error)
}

type walletServiceClient struct {
	cc *grpc.ClientConn
}

func NewWalletServiceClient(cc *grpc.ClientConn) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetUserWallet(ctx context.Context, in *WalletArg, opts ...grpc.CallOption) (*WalletMsg, error) {
	out := new(WalletMsg)
	err := c.cc.Invoke(ctx, "/models.WalletService/GetUserWallet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
type WalletServiceServer interface {
	GetUserWallet(context.Context, *WalletArg) (*WalletMsg, error)
}

// UnimplementedWalletServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWalletServiceServer struct {
}

func (*UnimplementedWalletServiceServer) GetUserWallet(ctx context.Context, req *WalletArg) (*WalletMsg, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserWallet not implemented")
}

func RegisterWalletServiceServer(s *grpc.Server, srv WalletServiceServer) {
	s.RegisterService(&_WalletService_serviceDesc, srv)
}

func _WalletService_GetUserWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletArg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetUserWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.WalletService/GetUserWallet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetUserWallet(ctx, req.(*WalletArg))
	}
	return interceptor(ctx, in, info, handler)
}

var _WalletService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserWallet",
			Handler:    _WalletService_GetUserWallet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "output.proto",
}
